# Generated by Django 3.0.10 on 2021-04-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_normal_beds', models.IntegerField(default=0)),
                ('normal_beds_occupied', models.IntegerField(default=models.IntegerField(default=0))),
                ('total_beds_with_ventilator', models.IntegerField(default=0)),
                ('ventilator_beds_occupied', models.IntegerField(default=models.IntegerField(default=0))),
                ('total_icu_beds', models.IntegerField(default=0)),
                ('icu_beds_occupied', models.IntegerField(default=models.IntegerField(default=0))),
                ('fire_safety_compliance', models.BooleanField(default=False)),
                ('hospital_contact_number', models.CharField(max_length=50, unique=True)),
                ('contact_person_name', models.CharField(max_length=50, unique=True)),
                ('contact_person_mobile', models.CharField(max_length=50, unique=True)),
                ('liason_officer_phone', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hospital.HospitalType')),
            ],
        ),
    ]
