# Generated by Django 3.0.10 on 2021-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='icu_beds_occupied',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='normal_beds_occupied',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='ventilator_beds_occupied',
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_beds_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='normal_beds_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ventilator_beds_available',
            field=models.IntegerField(default=0),
        ),
    ]
